### ISSUE TITLE
Add a migration guide for Terrajet -> Upjet

### ISSUE THREAD

**Issue by muvaf** [upbound/upjet#113]
### What problem are you facing?

Upjet originates from Terrajet but there are more features and some differences in the code that a short migration guide would be helpful.

### How could Upjet help solve your problem?

Add a migration guide talking about what provider developers need to do to use Upjet.

**Comment by muvaf** [comment]
Let's link the guide from README of Terrajet here https://github.com/crossplane/terrajet/blob/main/README.md

**Comment by ulucinar** [comment]
The [migration guide PR](https://github.com/upbound/upjet/pull/133) has been merged.

**Comment by ulucinar** [comment]
Terrajet repo README has now a reference to the guide:
https://github.com/crossplane/terrajet/pull/310

**Comment by ulucinar** [comment]
Closing this issue via the PRs https://github.com/upbound/upjet/pull/133 and https://github.com/crossplane/terrajet/pull/310.
