### ISSUE TITLE
Is generating-a-provider doc up do date?

### ISSUE THREAD

**Issue by IvanTurgenev1** [upbound/upjet#114]
### What problem are you facing?
The example has the following block of code :
```
pc := tjconfig.NewProviderWithSchema([]byte(providerSchema), resourcePrefix, modulePath,
    tjconfig.WithIncludeList([]string{
        "github_repository$",
        "github_branch$",
    }))
```
but in upjet template this code looks really different
```
	pc := tjconfig.NewProvider([]byte(providerSchema), resourcePrefix, modulePath, nil,
		tjconfig.WithIncludeList(ExternalNameConfigured()),
		tjconfig.WithDefaultResourceOptions(
			ExternalNameConfigurations(),
		))
```
is this doc need to be updated? or i did smth wrong?

**Comment by muvaf** [comment]
@IvanTurgenev1 The PR https://github.com/upbound/upjet/pull/115/ contains most up-to-date information including the TF provider documentation parsing for CRD API references!
