### ISSUE TITLE
Provider repository naming convention

### ISSUE THREAD

**Issue by sboschman** [upbound/upjet#120]
### What problem are you facing?

The 'Generating a Crossplane Provider' [docs](https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md) state:
> Generate a GitHub repository for the Crossplane provider by hitting the "Use this template" button in [upjet-provider-template](https://github.com/upbound/upjet-provider-template) repository.

My first inspiration is to name my provider repo 'upjet-provider-awesome'. The prepare script in step 3 names the go module `provider-awesome`, and updates all imports to `github.com/myorg/provider-awesome`. So the correct repository name is `provider-awesome` I guess. 

### How could Upjet help solve your problem?

If my assumption about the desired repository name (`provider-<name>`) is correct, it might be helpful to add this to the step 1 text.

**Comment by jeanduplessis** [comment]
@sboschman your assumption is correct about the preferred naming structure being `provider-<name>`. Do you feel comfortable opening a PR to make this clear in the docs?
