### ISSUE TITLE
Failed to scrape Terraform provider metadata: cannot scrape Terraform registry

### ISSUE THREAD

**Issue by IvanTurgenev1** [upbound/upjet#122]
### What happened?
I'm trying to generate provider followed by this guide: 
https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md
On generating-stage i am facing error:
scraper: error: Failed to scrape Terraform provider metadata: cannot scrape Terraform registry: failed to scrape resource metadata from path: ../.work/integrations/github/website/docs/r/actions_organization_permissions.html.markdown: failed to extract subcategory and title name of the resource

The main reason for the error is that the required field "subcategory"  is missing in the documentation for the github-provider. 
Also, not all providers have documentation for converting. Because of it this example-generation feature should be optional.

### How can we reproduce it?
Just follow step by step guide 
https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md

**Comment by jeanduplessis** [comment]
@IvanTurgenev1 can you clarify which Terraform provider you are trying to generate a provider for?

**Comment by turkenh** [comment]
I could reproduce this by following the guide. 

```
16:05:58 [ .. ] go generate linux_arm64
scraper: error: Failed to scrape Terraform provider metadata: cannot scrape Terraform registry: failed to scrape resource metadata from path: ../.work/integrations/github/website/docs/r/actions_environment_secret.html.markdown: failed to extract subcategory and title name of the resource
exit status 1
```

@ulucinar any idea on what could be wrong here?

**Comment by ulucinar** [comment]
@turkenh, in https://github.com/upbound/upjet-provider-template/pull/10, we are now consuming upjet's main HEAD, which contains a fix for the missing `subCategory` issue.
