### ISSUE TITLE
examples-generated not working for zscaler zpa

### ISSUE THREAD

**Issue by haarchri** [upbound/upjet#127]
### What happened?
repo: https://github.com/haarchri/provider-zscaler-zpa
terraform-provider: https://github.com/zscaler/terraform-provider-zpa

any ideas why the examples not generated ?

**Comment by luebken** [comment]
Thanks for the issue.

It might be fixed with https://github.com/upbound/upjet/pull/145. Would you mind testing it?

Setting severity to low as this only effects examples.

**Comment by haarchri** [comment]
is not working :/

**Comment by cdloh** [comment]
Also seeing this on Provider Cloudflare here @luebken - https://github.com/cdloh/provider-cloudflare

**Comment by cdloh** [comment]
@luebken I tell a complete lie. I've upgraded upjet on the repo manually and the scraper is now working as expected. I'm using the following commit - d381e878deea419c2d306c27e50cb401fdb2167e

**Comment by haarchri** [comment]
is also working here - thanks

`	github.com/upbound/upjet v0.8.0-rc.0.0.20230103094607-d381e878deea`

**Comment by jeanduplessis** [comment]
These issues should be resolved in the latest stable release of Upjet: https://github.com/upbound/upjet/releases/tag/v0.8.0
