### ISSUE TITLE
Move to terraform-json (CLI Schema) internally

### ISSUE THREAD

**Issue by turkenh** [upbound/upjet#131]
### What problem are you facing?

> Migrated from https://github.com/crossplane/terrajet/issues/262

Recently we [introduced](https://github.com/crossplane/terrajet/pull/174) generating resources from CLI schema with a conversion function which still converts input schema to SDK v2 schema. This was originally done to gradually move to the new schema and make sure it works fine.

We should completely move to [terraform-json](https://github.com/hashicorp/terraform-json) (CLI Schema) also as an internal representation to get rid of conversions and simplify the codebase. 

### How could Terrajet help solve your problem?

Use [terraform-json](https://github.com/hashicorp/terraform-json) as internal representation and remove dependency to Terraform SDK v2.

**Comment by ulucinar** [comment]
We are planning to return back to the Go schema to implement the no-fork architecture. Closing this issue for now...
