### ISSUE TITLE
state restoring not working?

### ISSUE THREAD

**Issue by IvanTurgenev1** [upbound/upjet#132]
### What happened?
deleting a pod or a state file from a pod does not restore the state file from etcd

I have a XR
```
"[crossplane.io/external-name](crossplane.io/external-name)": "1b0eb79c-d5e0-4b1e-b6b4-1fb4ec3912c0",
    "status": {
        "atProvider": {
            "externalIp": "",
            "id": "1b0eb79c-d5e0-4b1e-b6b4-1fb4ec3912c0",
            "internalIp": "100.126.0.124",
            "status": "ACTIVE"
        },
```
with proper external name config (e.g. IdentifierFromProvider)
But when state file is deleted(or pod is deleted) providers just create new instance and overwrite ID and IP to new ones

**Comment by IvanTurgenev1** [comment]
> @IvanTurgenev1 thanks for the issue.
> 
> As we discussed on the [slack thread](https://crossplane.slack.com/archives/C01718T2476/p1667296041549219), I tried to reproduce this with VPC of provider-aws but couldn't reproduced.
> 
> tfstate file is properly built with the correct Id after I removed it.
> 
> P.S: I tried did from my local, not with provider-aws running as a pod which I wouldn't expect to behave differently.
so seems like it's terraform provider bug or i did smth wrong
is it possibly to debug it? i mean get state from etcd or smth like it

**Comment by IvanTurgenev1** [comment]
so i'm trying to debug it...
there is my log with debug mode: on
```
 "metadata": {
        "annotations": {
       "crossplane.io/external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125",
}

   "status": {
        "atProvider": {
            "externalIp": "",
            "id": "442d7ba9-d878-4e83-a224-8a0084c1c125",
            "internalIp": "100.126.0.112",
            "status": "ACTIVE"
        },
        "conditions": [
            {
                "lastTransitionTime": "2022-11-01T19:08:35Z",
                "reason": "Available",
                "status": "True",
                "type": "Ready"
            },
            {
                "lastTransitionTime": "2022-11-01T19:07:46Z",
                "reason": "ReconcileSuccess",
                "status": "True",
                "type": "Synced"
            },
            {
                "lastTransitionTime": "2022-11-01T19:08:29Z",
                "reason": "Finished",
                "status": "True",
                "type": "AsyncOperation"
            },
            {
                "lastTransitionTime": "2022-11-01T19:08:29Z",
                "reason": "Success",
                "status": "True",
                "type": "LastAsyncOperation"
            }
        ]
    }
}
```

<details>
  <summary>Reconciling loop </summary>
1.66732979062848e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.6673297936936698e+09	DEBUG	provider-salt	refresh ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:50.666265+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refreshing state... [id=442d7ba9-d878-4e83-a224-8a0084c1c125]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:51.194939+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"442d7ba9-d878-4e83-a224-8a0084c1c125\"},\"type\":\"refresh_start\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refresh complete [id=442d7ba9-d878-4e83-a224-8a0084c1c125]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:53.668813+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"442d7ba9-d878-4e83-a224-8a0084c1c125\"},\"type\":\"refresh_complete\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:53.671275+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:53.691575+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:53.691606+03:00\",\"outputs\":{},\"type\":\"outputs\"}\n"}
1.667329794323322e+09	DEBUG	provider-salt	plan ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:53.722280+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:09:54.321438+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n"}
1.6673297943234031e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811115", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "requeue-after": 1667329854.323402} 
</details>

so as we can see, external name is our id..

But what should happen when we delete a tfstate file?
<details>
  <summary>Reconciling loop </summary> 
1.6673298543378181e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329854941382e+09	DEBUG	provider-salt	refresh ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:54.368137+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:54.916457+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:54.938805+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:54.938849+03:00\",\"outputs\":{},\"type\":\"outputs\"}\n"}
1.667329854982773e+09	DEBUG	provider-salt	Successfully requested creation of external resource	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811115", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125"}
1.667329854982947e+09	DEBUG	events	Normal	{"object": {"kind":"Instance","name":"testinst","uid":"dbac2e4a-8780-4954-bb92-ec6f34d768cc","apiVersion":"instance.salt.upbound.io/v1alpha1","resourceVersion":"811353"}, "reason": "CreatedExternalResource", "message": "Successfully requested creation of external resource"}
1.667329854994787e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329854994949e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811354", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "requeue-after": 1667329914.9949481}
1.66732985500427e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329855004385e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811356", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "requeue-after": 1667329915.004384}
1.667329855994907e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329855995127e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811356", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "requeue-after": 1667329915.995125}
1.6673298975035021e+09	DEBUG	provider-salt	apply async ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:54.984946+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Plan to create\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:55.576164+03:00\",\"change\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\"},\"type\":\"planned_change\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 1 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:55.576229+03:00\",\"changes\":{\"add\":1,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Creating...\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:10:55.915225+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\"},\"type\":\"apply_start\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Still creating... [10s elapsed]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:05.916601+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\",\"elapsed_seconds\":10},\"type\":\"apply_progress\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Still creating... [20s elapsed]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:15.917273+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\",\"elapsed_seconds\":20},\"type\":\"apply_progress\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Still creating... [30s elapsed]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:25.917907+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\",\"elapsed_seconds\":30},\"type\":\"apply_progress\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Still creating... [40s elapsed]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:35.918475+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\",\"elapsed_seconds\":40},\"type\":\"apply_progress\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Creation complete after 41s [id=1948b337-e800-4dac-964a-0e74e507bb83]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.453971+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"action\":\"create\",\"id_key\":\"id\",\"id_value\":\"1948b337-e800-4dac-964a-0e74e507bb83\",\"elapsed_seconds\":41},\"type\":\"apply_complete\"}\n{\"@level\":\"warn\",\"@message\":\"Warning: Status VM does not success yet.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.500262+03:00\",\"diagnostic\":{\"severity\":\"warning\",\"summary\":\"Status VM does not success yet.\",\"detail\":\"Actually VM is in \\\"BUILD\\\" status\",\"address\":\"salt_compute_instance.testinst\",\"range\":{\"filename\":\"main.tf.json\",\"start\":{\"line\":1,\"column\":485,\"byte\":484},\"end\":{\"line\":1,\"column\":486,\"byte\":485}},\"snippet\":{\"context\":\"resource.salt_compute_instance.testinst\",\"code\":\"{\\\"provider\\\":{\\\"salt\\\":{\\\"password\\\":\\\"REDACTED\\\",\\\"username\\\":\\\"REDACTED\\\"}},\\\"resource\\\":{\\\"salt_compute_instance\\\":{\\\"testinst\\\":{\\\"disks\\\":[{\\\"boot\\\":true,\\\"description\\\":null,\\\"disk_id\\\":null,\\\"name\\\":\\\"mydisk\\\",\\\"size\\\":10,\\\"type\\\":\\\"ceph\\\"}],\\\"flavor_name\\\":\\\"m1.small\\\",\\\"image_name\\\":\\\"x5-Centos_7\\\",\\\"key\\\":\\\"\\\",\\\"lifecycle\\\":{\\\"prevent_destroy\\\":true},\\\"name\\\":\\\"myvm\\\",\\\"networks_name\\\":\\\"frontend\\\",\\\"project_id\\\":\\\"dceecdf7-d1da-4128-a33d-742e1247a660\\\",\\\"security_groups\\\":[\\\"any\\\"],\\\"tags\\\":[\\\"mytag\\\"],\\\"usual_vm\\\":true}}},\\\"terraform\\\":{\\\"required_providers\\\":{\\\"salt\\\":{\\\"source\\\":\\\"salt\\\",\\\"version\\\":\\\"0.0.15\\\"}}}}\",\"start_line\":1,\"highlight_start_offset\":484,\"highlight_end_offset\":485,\"values\":[]}},\"type\":\"diagnostic\"}\n{\"@level\":\"warn\",\"@message\":\"Warning: Warning during polling. Does not require a reaction.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.500612+03:00\",\"diagnostic\":{\"severity\":\"warning\",\"summary\":\"Warning during polling. Does not require a reaction.\",\"detail\":\"warning: VM is not active\",\"address\":\"salt_compute_instance.testinst\",\"range\":{\"filename\":\"main.tf.json\",\"start\":{\"line\":1,\"column\":485,\"byte\":484},\"end\":{\"line\":1,\"column\":486,\"byte\":485}},\"snippet\":{\"context\":\"resource.salt_compute_instance.testinst\",\"code\":\"{\\\"provider\\\":{\\\"salt\\\":{\\\"password\\\":\\\"REDACTED\\\",\\\"username\\\":\\\"REDACTED\\\"}},\\\"resource\\\":{\\\"salt_compute_instance\\\":{\\\"testinst\\\":{\\\"disks\\\":[{\\\"boot\\\":true,\\\"description\\\":null,\\\"disk_id\\\":null,\\\"name\\\":\\\"mydisk\\\",\\\"size\\\":10,\\\"type\\\":\\\"ceph\\\"}],\\\"flavor_name\\\":\\\"m1.small\\\",\\\"image_name\\\":\\\"x5-Centos_7\\\",\\\"key\\\":\\\"\\\",\\\"lifecycle\\\":{\\\"prevent_destroy\\\":true},\\\"name\\\":\\\"myvm\\\",\\\"networks_name\\\":\\\"frontend\\\",\\\"project_id\\\":\\\"dceecdf7-d1da-4128-a33d-742e1247a660\\\",\\\"security_groups\\\":[\\\"any\\\"],\\\"tags\\\":[\\\"mytag\\\"],\\\"usual_vm\\\":true}}},\\\"terraform\\\":{\\\"required_providers\\\":{\\\"salt\\\":{\\\"source\\\":\\\"salt\\\",\\\"version\\\":\\\"0.0.15\\\"}}}}\",\"start_line\":1,\"highlight_start_offset\":484,\"highlight_end_offset\":485,\"values\":[]}},\"type\":\"diagnostic\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 1 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.500662+03:00\",\"changes\":{\"add\":1,\"change\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.500682+03:00\",\"outputs\":{},\"type\":\"outputs\"}\n"}
1.6673298975148318e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329900505342e+09	DEBUG	provider-salt	refresh ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:37.547053+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refreshing state... [id=1948b337-e800-4dac-964a-0e74e507bb83]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:38.274528+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"1948b337-e800-4dac-964a-0e74e507bb83\"},\"type\":\"refresh_start\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refresh complete [id=1948b337-e800-4dac-964a-0e74e507bb83]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:40.476401+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"1948b337-e800-4dac-964a-0e74e507bb83\"},\"type\":\"refresh_complete\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:40.480402+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:40.502034+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:40.502102+03:00\",\"outputs\":{},\"type\":\"outputs\"}\n"}
1.66732990051917e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811429", "external-name": "442d7ba9-d878-4e83-a224-8a0084c1c125", "requeue-after": 1667329960.519168}
1.667329900529925e+09	DEBUG	provider-salt	Reconciling	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst"}
1.667329903488842e+09	DEBUG	provider-salt	refresh ended	{"workspace": "/var/folders/3l/7f57_gn93fz_30vl3ztzm_440000gp/T/dbac2e4a-8780-4954-bb92-ec6f34d768cc", "out": "{\"@level\":\"info\",\"@message\":\"Terraform 1.2.9\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:40.563291+03:00\",\"terraform\":\"1.2.9\",\"type\":\"version\",\"ui\":\"1.0\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refreshing state... [id=1948b337-e800-4dac-964a-0e74e507bb83]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:41.131373+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"1948b337-e800-4dac-964a-0e74e507bb83\"},\"type\":\"refresh_start\"}\n{\"@level\":\"info\",\"@message\":\"salt_compute_instance.testinst: Refresh complete [id=1948b337-e800-4dac-964a-0e74e507bb83]\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:43.461647+03:00\",\"hook\":{\"resource\":{\"addr\":\"salt_compute_instance.testinst\",\"module\":\"\",\"resource\":\"salt_compute_instance.testinst\",\"implied_provider\":\"salt\",\"resource_type\":\"salt_compute_instance\",\"resource_name\":\"testinst\",\"resource_key\":null},\"id_key\":\"id\",\"id_value\":\"1948b337-e800-4dac-964a-0e74e507bb83\"},\"type\":\"refresh_complete\"}\n{\"@level\":\"info\",\"@message\":\"Plan: 0 to add, 0 to change, 0 to destroy.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:43.464660+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"plan\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Apply complete! Resources: 0 added, 0 changed, 0 destroyed.\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:43.486680+03:00\",\"changes\":{\"add\":0,\"change\":0,\"remove\":0,\"operation\":\"apply\"},\"type\":\"change_summary\"}\n{\"@level\":\"info\",\"@message\":\"Outputs: 0\",\"@module\":\"terraform.ui\",\"@timestamp\":\"2022-11-01T22:11:43.486705+03:00\",\"outputs\":{},\"type\":\"outputs\"}\n"}
1.667329903489245e+09	DEBUG	provider-salt	External resource is up to date	{"controller": "managed/instance.salt.upbound.io/v1alpha1, kind=instance", "request": "/testinst", "uid": "dbac2e4a-8780-4954-bb92-ec6f34d768cc", "version": "811436", "external-name": "1948b337-e800-4dac-964a-0e74e507bb83", "requeue-after": 1667329963.4892428} 
</details>

**Comment by turkenh** [comment]
Just filed a bug which could be relevant: https://github.com/upbound/provider-aws/issues/123
