### ISSUE TITLE
Sensitive maps should not have struct as value type

### ISSUE THREAD

**Issue by muvaf** [upbound/upjet#134]
### What happened?

Kubernetes API conventions suggest that value type of maps should be basic types, like string or integer. In case it needs to be a struct, it should be a [named list](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#lists-of-named-subobjects-preferred-over-maps).

> There are no maps of subobjects in any API objects. Instead, the convention is to use a list of subobjects containing name fields.

However, Upjet generates a `map[string]v1.SecretKeySelector` for maps that are marked as sensitive such as `connection_properties` field of `aws_glue_connection` whose schema looks like the following:
```golang
"connection_properties": {
  Type:         schema.TypeMap,
  Optional:     true,
  Sensitive:    true,
  ValidateFunc: mapKeyInSlice(glue.ConnectionPropertyKey_Values(), false),
  Elem:         &schema.Schema{Type: schema.TypeString},
}
```

There relevant code is [here](https://github.com/upbound/upjet/blob/d8c3541/pkg/types/field.go#L172).

### How can we reproduce it?

Look at `aws_glue_connection` CRD.

### Proposed Solution

I think we have two options.
* A slice with two fields `name` and `secretRef` where `name` is the key and the value is taken from the referenced secret.
* A `SecretReference` that for the whole map and take the map under `data` field and use it.

In the `aws_glue_connection`, the map keys are connection details like URL, password etc. IMO, these are usually in the same secret and it'd be a better UX if users just supplied that one `Secret`.

**Comment by turkenh** [comment]
I agree that option 2 is better UX-wise. I cannot think of a reason not to go with it given data field of secret is also a map.
