### ISSUE TITLE
resources and resource files can conflict with go-lang reserved keywords

### ISSUE THREAD

**Issue by srust** [upbound/upjet#139]
### What happened?

Hi,

There a few problems that occur if an imported resource name or field in a resource overlaps with a go-lang reserved keyword.

For example, "range".

This affects the *typewriter* generated files that are produced as well, and filed here https://github.com/muvaf/typewriter/pull/11

However, several other generated files done by *upjet* hit this issue in perhaps a more architecturally challenging way.

```
15:16:19 [ .. ] go generate linux_amd64
panic: cannot run goimports for internal folder: ./controller/ipv6_range/range/zz_controller.go:7:9: expected 'IDENT', found 'range'
./controller/ipv6_range/range/zz_controller.go:9:1: expected ';', found 'import'
: exit status 2
```

And this is because the package name becomes a reserved keyword in this file

```
    1 /*
    2 Copyright 2022 Upbound Inc.
    3 */
    4
    5 // Code generated by upjet. DO NOT EDIT.
    6
    7 package range
```
### How can we reproduce it?

The field in question is here:

https://registry.terraform.io/providers/linode/linode/latest/docs/resources/ipv6_range#range

I can provide a provider repo with this error if that is helpful.

Thank you!

Please let me know how I can help resolve this issue.

**Comment by ulucinar** [comment]
Hi @srust,
Thank you for reporting this issue. It would be helpful if you could provide the provider repo as you suggested so that we could work together on a workaround.

**Comment by ulucinar** [comment]
What you could do as a workaround is to use the resource configuration API to override the generated `Kind` name and, if needed, the short group name. You can override the generated `Kind` name with [`config.Resource.Kind`](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/resource.go#L277) and the short group name with [`config.Resource.ShortGroup `](https://github.com/upbound/upjet/blob/606a1db65fa2c6daa3f1958b8384df2ffcbcc71e/pkg/config/resource.go#L271).

**Comment by srust** [comment]
Hi @ulucinar thanks!

Indeed the `config.Resources.Kind` is able to workaround this issue.

The provider we are developing is at https://github.com/linode/provider-linode

All of the available terraform resources are included in that provider now, except for the `ipv6_range` resource.

I have a branch that includes support for `ipv6_range` but requires the Kind override in order to generate properly.

This is available at https://github.com/srust/provider-linode/tree/ipv6_range

If the `config/ipv6range/config.go` is edited to remove the `r.Kind` specification, then syntax errors occur:

```
diff --git a/config/ipv6range/config.go b/config/ipv6range/config.go
index f16a5d0..ca62cb0 100644
--- a/config/ipv6range/config.go
+++ b/config/ipv6range/config.go
@@ -7,6 +7,5 @@ func Configure(p *config.Provider) {
        p.AddResourceConfigurator("linode_ipv6_range", func(r *config.Resource) {
                // We need to override the default group that upjet generated for
                // this resource, which would be "linode"
-               r.Kind = "IPv6range"
        })
 }

$ make generate
12:53:31 [ .. ] generating provider schema for linode/linode 1.29.4
12:53:33 [ OK ] generating provider schema for linode/linode 1.29.4
12:53:33 [ .. ] verify go modules dependencies have expected content
all modules verified
12:53:35 [ OK ] go modules dependencies verified
12:53:36 [ .. ] go generate linux_amd64
panic: cannot run goimports for internal folder: ./controller/zz_setup.go:16:1: expected 'STRING', found 'range'
./controller/zz_setup.go:47:2: expected 'STRING', found 'for'
./controller/zz_setup.go:78:3: expected 'STRING', found 'if'
./controller/zz_setup.go:79:4: expected 'STRING', found 'return'
./controller/zz_setup.go:82:2: expected 'STRING', found 'return'
./controller/zz_setup.go:83:3: expected ')', found 'EOF'
./controller/ipv6/range/zz_controller.go:7:9: expected 'IDENT', found 'range'
./controller/ipv6/range/zz_controller.go:9:1: expected ';', found 'import'
: exit status 2

goroutine 1 [running]:
github.com/upbound/upjet/pkg/pipeline.Run(0xc000505800, {0xc000448940, 0x34})
	/Users/srust/go/pkg/mod/github.com/upbound/upjet@v0.8.0-rc.0.0.20221115075453-606a1db65fa2/pkg/pipeline/run.go:126 +0xae5
main.main()
	/Users/srust/go/src/github.com/srust/provider-linode/cmd/generator/main.go:26 +0x74
exit status 2
```

Thanks!

**Comment by ulucinar** [comment]
Thank you @srust for the full context. Because you've already opened an issue in the upstream dependency, I would suggest closing this one. My understanding is that the affected Terraform resources are the ones with a Go reserved keyword suffix. If an upstream fix is introduced, then we can try consuming it in upjet. What do you think?

**Comment by srust** [comment]
I am fine closing this. The workaround is to be honest sufficient for our use-case. Perhaps there is some documentation that should be updated to show the `config.Resource.Kind` workaround, to help some new users. It did take a bit of digging to find the generated code and what was causing the compile failure.
