### ISSUE TITLE
Field marked sensitive in terraform provider throws error while converting to crossplane

### ISSUE THREAD

**Issue by AnushaSN** [upbound/upjet#183]
### What happened?

While trying to generate a CRD for resource:
https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test

there is error due to mismatch of datatype.ie the client id is marked sensitive in datadog.(https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test#nested-schema-for-options_listrum_settings)

panic: cannot generate crd for resource datadog_synthetics_test: cannot build types for Test: cannot build the Types: cannot infer type from schema of field options_list: cannot infer type from resource schema of element type of Test.OptionsList: cannot infer type from schema of field rum_settings: cannot infer type from resource schema of element type of Test.OptionsList.RumSettings: got type "*float64" for field "ClientTokenID", only types "string", "*string", []string, []*string, "map[string]string" and "map[string]*string" supported as sensitive

### How can we reproduce it?

following steps under generate provider(https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md)
 from an existing terraform provider(datadog: https://registry.terraform.io/providers/DataDog/datadog/latest)

add resource https://registry.terraform.io/providers/DataDog/datadog/latest/docs/resources/synthetics_test by following steps under add new resource: 
https://github.com/upbound/upjet/blob/main/docs/add-new-resource-short.md

and then make generate - which will throw the above error while creating crds

the following are the parameters in Makefile:

export TERRAFORM_VERSION := 1.3.3
export TERRAFORM_PROVIDER_SOURCE := DataDog/datadog
export TERRAFORM_PROVIDER_REPO := https://github.com/DataDog/terraform-provider-datadog
export TERRAFORM_PROVIDER_VERSION := 3.23.0
export TERRAFORM_PROVIDER_DOWNLOAD_NAME := terraform-provider-datadog
export TERRAFORM_NATIVE_PROVIDER_BINARY := terraform-provider-datadog_3.23.0
export TERRAFORM_DOCS_PATH := docs/resources

**Comment by turkenf** [comment]
Hi @AnushaSN, thank you for raising this issue, we have updated the Generating a Crossplane Provider document, could you please try again and let us know if you run into any issues?

**Comment by jeanduplessis** [comment]
I'm closing this issue for now. If the problem still persists, feel free to add a comment again.
