### ISSUE TITLE
Guide to generate a provider from scratch seems broken

### ISSUE THREAD

**Issue by dnlopes** [upbound/upjet#198]
### What happened?
I'm trying to generate a provider from scratch, [following this guide](https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md) (in this case the Vault provider) without success. To minimize entropy, I also tried to follow the example as is (i.e., generate the provider in the example, which is GitHub), but had the exact same error when running `make generate`

### How can we reproduce it?
Follow the until the end, and after running `make generate` the following error appears:

```bash
13:57:21 [ .. ] generating provider schema for integrations/github 5.5.0
13:57:22 [ OK ] generating provider schema for integrations/github 5.5.0
13:57:22 [ .. ] verify go modules dependencies have expected content
all modules verified
13:58:31 [ OK ] go modules dependencies verified
13:58:31 [ .. ] go generate linux_amd64
go: warning: "github.com/upbound/provider-github/cmd/..." matched no packages
go: warning: "github.com/upbound/provider-github/internal/..." matched no packages
go: warning: "github.com/upbound/provider-github/apis/..." matched no packages
13:58:32 [ OK ] go generate linux_amd64
13:58:32 [ .. ] go mod tidy
go: finding module for package github.com/OutSystems/provider-github/apis/null/v1alpha1
github.com/OutSystems/provider-github/apis imports
        github.com/OutSystems/provider-github/apis/null/v1alpha1: no matching versions for query "latest"
13:58:37 [FAIL]
make[1]: *** [go.generate] Error 1
make: *** [generate] Error 2
```

**Comment by svscheg** [comment]
Hi @dnlopes ! Thank you for reporting bug.

Unfortunately I can't reproduce the issue on my local env (MacBook Pro, macOs Ventura version 13.2.1)
![Image](https://github.com/upbound/upjet/assets/114226153/8a508f39-2eda-4bbe-b170-ec2ccc6225bf)

Could you please provide more information like OS, version, etc.

**Comment by dimq** [comment]
Hi there, I just got the same error. 
I reproduce it in the codespace of my forked template repository. 
`Go Version 1.19.9
Main branch of the repository`

I supposed some error while running the `./hack/prepare.sh` ? I noticed some bad returns from the sed commands : 
```
+ REPLACE_FILES='./* ./.github :!build/** :!go.* :!hack/prepare.sh'
+ xargs sed -i.bak s/upjet-provider-template/provider-outscale/g
+ git grep -l template -- ./CODEOWNERS ./CODE_OF_CONDUCT.md ./LICENSE ./Makefile ./Makefile.bak ./OWNERS.md ./README.md ./apis ./build ./cluster ./cmd ./config ./examples ./go.mod ./go.mod.bak ./go.sum ./hack ./internal ./package ./.github ':!build/**' ':!go.*' ':!hack/prepare.sh'
sed: no input files
```

I don't know if the sed command should get rid of the null example present in the template repository ?
With a little grep : 
```
@dimq ➜ /workspaces/provider-outscale (main) $ grep -rI "github.com/dimq/provider-outscale/apis/null/v1alpha1" .
./internal/controller/null/resource/zz_controller.go:   v1alpha1 "github.com/dimq/provider-outscale/apis/null/v1alpha1"
./apis/zz_register.go:  v1alpha1 "github.com/dimq/provider-outscale/apis/null/v1alpha1"
```
I can find two occurrences of this wrongly named path.

Not sure what other information I can provide, but don't hesitate.

**Comment by turkenf** [comment]
Hi @dimq, we updated the guide please try again. Please make sure all null files and configurations are removed and make sure the `PROJECT_REPO ?= [github.com/](http://github.com/)<YOUR_ORG>/$(PROJECT_NAME)`  your org on line 5 in the Makefile is correct.

**Comment by dimq** [comment]
Perfect for me thanks!
