### ISSUE TITLE
Description is not allowed to be empty

### ISSUE THREAD

**Issue by Breee** [upbound/upjet#219]
### What happened?

https://github.com/upbound/upjet/blob/018e6404baef55366ddd86d8d9cbf04c9bcb2426/pkg/registry/resource.go#L45 states that description can be empty,  however,  it seems to break if the description field is missing in terraform docs

### How can we reproduce it?

https://github.com/upbound/upjet-provider-template/issues/32

**Comment by turkenf** [comment]
Hi @Breee,

Thank you for raising this issue. I could not establish a connection between the issue you gave to reproduce and the issue you mentioned here. 

If you are having a similar problem, I left a [comment](https://github.com/upbound/upjet-provider-template/issues/32#issuecomment-1592860342), it may solve your problem as well.
