### ISSUE TITLE
Upgrade Go version to 1.20

### ISSUE THREAD

**Issue by s-vo** [upbound/upjet#232]
### What problem are you facing?

User has to move down from Go 1.20 to 1.9 to work with the latest upjet.  The request is to support Go 1.20 which was released on 2023-02-01 and has gone through 6 minor releases.

**Comment by jeanduplessis** [comment]
@s-vo we are going to move to Go 1.20 once this PR lands: https://github.com/upbound/upjet/pull/224/files

**Comment by jeanduplessis** [comment]
@s-vo We've landed a PR upgrading to Go 1.20: https://github.com/upbound/upjet/pull/236

**Comment by s-vo** [comment]
@jeanduplessis awesome! thank you.
