### ISSUE TITLE
observe failed

### ISSUE THREAD

**Issue by Valerianer** [upbound/upjet#246]
### What happened?
I tried to use the [upjet-provider-template](https://github.com/upbound/upjet-provider-template) for implementing an artifactory-provider with the [terraform-artifactory-provider](https://registry.terraform.io/providers/jfrog/artifactory/latest/docs). While creation of repositories is working pretty well, the creation of an artifactory-user fails within this Method:
Refresh-Method
* Observe()
  * Refresh()
    * runTF( ... "apply", "-refresh-only", "-auto-approve", "-input=false", "-lock=false", "-json") << this method is throwing the error in the end since the log-entry starting with "refresh ended" contains the following error: 

```
{
    "@level": "error",
    "@message": "Error: Unable to Refresh Resource",
    "@module": "terraform.ui",
    "@timestamp": "2023-07-28T11:23:08.130707Z",
    "diagnostic": {
        "address": "artifactory_user.crossplane-user",
        "detail": "An unexpected error occurred while attempting to refresh resource state. Please retry the operation or report this issue to the provider developers.HTTP Error: 404 GET REDACTED/api/security/users/crossplane-user{"errors": [ {    "status" : 404,    "message" : "Not Found"  } ]}",
        "range": {
            "end": {
                "byte": 399,
                "column": 400,
                "line": 1
            },
            "filename": "main.tf.json",
            "start": {
                "byte": 398,
                "column": 399,
                "line": 1
            }
        },
        "severity": "error",
        "snippet": {
            "code": {
                "provider": {
                    "artifactory": {
                        "access_token": "REDACTED",
                        "url": "REDACTED"
                    }
                },
                "resource": {
                    "artifactory_user": {
                        "crossplane-user": {
                            "admin": false,
                            "disable_ui_access": false,
                            "email": "crossplane-user@example.com",
                            "internal_password_disabled": true,
                            "lifecycle": {
                                "prevent_destroy": true
                            },
                            "name": "crossplane-user"
                        }
                    }
                },
                "terraform": {
                    "required_providers": {
                        "artifactory": {
                            "source": "jfrog/artifactory",
                            "version": "8.3.0"
                        }
                    }
                }
            },
            "context": "resource.artifactory_user.crossplane-user",
            "highlight_end_offset": 399,
            "highlight_start_offset": 398,
            "start_line": 1,
            "values": []
        },
        "summary": "Unable to Refresh Resource"
    },
    "type": "diagnostic"
}
```
("\n" and "\\" from log removed)

### How can we reproduce it?
terraform-version 2.5.1
terraform-artifactory-provider: 8.3.0

* create crossplane-provider based on the template and terraform-provider mentioned above
* ExternalNameConfigs configured with `"artifactory_user": config.NameAsIdentifier,`
* apply a custom-resource for a artifactory-user

### Additional:
* Also the hint for [lateInitialisation](https://github.com/upbound/upjet/blob/main/docs/add-new-resource-long.md#late-initialization-configuration) seems not to match, since this error occurs before the check of the async-mode...
* If I go into the provider-shell, remove the terraform.tf-statefile and run the terraform-command directly withe args metioned above, the refresh works... >> That means, out of any reason the controller tries to get the resource from the external system befor it gets created, which doesn't make sense of course. I was still not able to determine why it behaves like that...

**Comment by Valerianer** [comment]
After some further research it pointed out, that the error is located at the terraform-provider. Closing the issue.

**Comment by suvaanshkumar** [comment]
Hi @chris-tian89 , 
Were you able to generate the provider?
Me and my team are planning to use one and have started with a small initiative [here](https://github.com/suvaanshkumar/provider-jfrogartifactory). Please let me know if there is any information that can be useful for developing this provider.
