### ISSUE TITLE
./hack/prepare.sh script not working

### ISSUE THREAD

**Issue by ranour93** [upbound/upjet#264]
I followed the steps in this documentation: https://github.com/upbound/upjet/blob/main/docs/generating-a-provider.md
to create my own crossplane provider from a terraform provider. I ran into this error with the ./hack/prepare.sh script: 

+ read -r -p 'Lower case provider name (ex. github): ' PROVIDER_NAME_LOWER
Lower case provider name (ex. github): xxxxx
+ read -r -p 'Normal case provider name (ex. GitHub): ' PROVIDER_NAME_NORMAL
Normal case provider name (ex. GitHub): xxxxx
+ read -r -p 'Organization (ex. xxxxx, my-org-name): ' ORGANIZATION_NAME
Organization (ex. xxxxxx, my-org-name): xxxxxx
+ read -r -p 'CRD rootGroup (ex. xxxxxxx.io, crossplane.io): ' CRD_ROOT_GROUP
CRD rootGroup (ex. xxxxxxxx.io, crossplane.io): xxxxxxxxxx.io
+ REPLACE_FILES='./* ./.github :!build/** :!go.* :!hack/prepare.sh'
+ git grep -l template -- ./apis ./build ./cluster ./cmd ./CODE_OF_CONDUCT.md ./CODEOWNERS ./config ./examples ./go.mod ./go.sum ./hack ./internal ./LICENSE ./Makefile ./Makefile.bak ./OWNERS.md ./package ./README.md ./README.md.bak ./scripts ./.github ':!build/**' ':!go.*' ':!hack/prepare.sh'
+ xargs sed -i.bak s/upjet-provider-template/provider-xxxxxx/g
sed: no input files

Any suggestions on how I can proceed?

**Comment by turkenf** [comment]
Hi @ranour93, thank you for raising this issue, 

Can you give us more information so that we can fully understand the issue, and which provider are you working on?

**Comment by haarchri** [comment]
@ranour93 which OS you using ?

**Comment by ranour93** [comment]
I'm using Rocky 9 and I'm trying to create a crossplane provider for libvirt using upjet from this libvirt terraform provider: https://registry.terraform.io/providers/dmacvicar/libvirt/latest/docs

I can't seem to get to prepare.sh script to work when I put in the provider name and organization name as inputs. I receive the sed error above saying there are no input files.

**Comment by haarchri** [comment]
add an PR for this error: https://github.com/upbound/upjet-provider-template/pull/56
