### ISSUE TITLE
`google_kms_key_*` example *.yaml not generated

### ISSUE THREAD

**Issue by Piotr1215** [upbound/upjet#74]
### What happened?

Following KMS resources
- `google_kms_key_ring_import_job`
- `google_kms_key_ring_iam_member`
- `google_kms_crypto_key_iam_member`

had no example `*.yaml` files automatically generated. 
The resources are not on `skipList` and TF Provider version match. The configuration is correct and example files were generated manually.
What other reasons could there be for it not to generate an example file?

### How can we reproduce it?

1. Configure the resource
2. Run `make generate` or `make reviewable`

#### Expected behaviour 

Examples file are generated in the <kbd>example-generated/kms</kbd> folder.

#### Actual behaviour

Files are not generated. No error in the `make run` output.

PR to help reproduce the issue: https://github.com/upbound/official-providers/pull/577

**Comment by turkenf** [comment]
Since we now have the specified [resources](https://github.com/upbound/provider-gcp/tree/main/examples/kms) we can close this issue.
