### ISSUE TITLE
Ref and Selector field documentation should include the target type

### ISSUE THREAD

**Issue by muvaf** [upbound/upjet#77]
### What problem are you facing?

It's hard to figure out which CRD they can reference or select just by looking at the field name

### How could Terrajet help solve your problem?

We can add type name to field doc when we add these fields to the struct.

**Comment by ulucinar** [comment]
I think we now have this documentation in the generated OpenAPI v3 schema. An [example]()https://github.com/upbound/provider-aws/blob/main/package/crds/kinesis.aws.upbound.io_streamconsumers.yaml#L116C59-L116C59 is:
<img width="727" alt="image" src="https://github.com/upbound/upjet/assets/9376684/fa661021-654d-473d-945b-4a6aaac1fcc3">
